### PR TITLE
fix: remote hypervisor snapshot creation

### LINKED ISSUE #68: `vmware-iso`: Using the `snapshot_name` option with ESXi, the VMX file does not refer the correct snapshot
I use packer to generate virtual machines on ESXi.

I set a [snapshot_name](https://www.packer.io/plugins/builders/vmware/iso#snapshot_name) combined with `"keep_registered": true` and  `"skip_export": true`.

Packer succeed to create the Virtual Machine and the snapshot is created indeed but the VMX file does refer the snapshot:

  * Actual result:
    ```
    scsi0:0.filename = "disk.vmdk"
    ```

  * Expected result:
    ```
    scsi0:0.filename = "disk-000001.vmdk"
    ```

Related to #20

### PR DESCRIPTION
**Pull request by tenthirtyam**
### Description

Moves the snapshot creation step after the upload of the `.vmx` file to the remote hypervisor. When not set in this order, the virtual machine will not be set to run on the created snapshot.

### Testing

General

```console
packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 took 3.4s 
➜ go fmt ./...

packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 
➜ make generate
2024/07/15 22:04:53 Copying "docs" to ".docs/"
2024/07/15 22:04:53 Replacing @include '...' calls in .docs/
Compiling MDX docs in '.docs' to Markdown in '.web-docs'...

packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 took 2.9s 
➜ make build

packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 
➜ make test
?       github.com/hashicorp/packer-plugin-vmware       [no test files]
?       github.com/hashicorp/packer-plugin-vmware/version       [no test files]
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/common 6.714s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/iso    2.550s
ok      github.com/hashicorp/packer-plugin-vmware/builder/vmware/vmx    2.020s

packer-plugin-vmware on  fix/snapshot-creation [$!] via 🐹 v1.22.5 took 10.4s 
➜ make dev 
packer plugins install --path packer-plugin-vmware "github.com/hashicorp/vmware"
Successfully installed plugin github.com/hashicorp/vmware from /Users/ryan/Library/Mobile Documents/com~apple~CloudDocs/Code/Personal/packer-plugin-vmware/packer-plugin-vmware to /Users/ryan/.packer.d/plugins/github.com/hashicorp/vmware/packer-plugin-vmware_v1.0.12-dev_x5.0_darwin_arm64
```

Run

```console
==> vmware-iso.appliance: Deleting unnecessary VMware files...
    vmware-iso.appliance: Deleting: /vmfs/volumes/local/appliance/appliance.scoreboard
    vmware-iso.appliance: Deleting: /vmfs/volumes/local/appliance/vmware.log
==> vmware-iso.appliance: Cleaning VMX prior to finishing up...
    vmware-iso.appliance: Detaching ISO from CD-ROM device ide0:0...
    vmware-iso.appliance: Detaching ISO from CD-ROM device ide1:0...
    vmware-iso.appliance: Disabling VNC server...
==> vmware-iso.appliance: Creating snapshot of the virtual machine...
==> vmware-iso.appliance: Skipping export of virtual machine...
Build 'vmware-iso.appliance' finished after 2 minutes 29 seconds.

==> Wait completed after 2 minutes 29 seconds

==> Builds finished. The artifacts of successful builds are:
--> vmware-iso.appliance: VM files in directory: /vmfs/volumes/local/appliance
```

```text
sata0.present = "FALSE"
scsi0.pcislotnumber = "16"
scsi0.present = "TRUE"
scsi0.virtualdev = "pvscsi"
scsi0:0.filename = "disk-000001.vmdk" <--- expected result.
scsi0:0.present = "TRUE"
scsi0:0.redo = ""
```

### Reference

Closes #68

### CODE REVIEW

File: builder/vmware/common/step_create_snapshot.go [hunk 1]
```diff
@@ -11,17 +11,19 @@ import (
...
+// StepCreateSnapshot step creates a snapshot for the virtual machine after the
+// build has been completed.
 type StepCreateSnapshot struct {
 	SnapshotName *string
 }
 
 func (s *StepCreateSnapshot) Run(ctx context.Context, state multistep.StateBag) multistep.StepAction {
-	if *s.SnapshotName != "" { // if snapshot name is set create one, if not don't
+	// If snapshot name is set, create snapshot.
+	if *s.SnapshotName != "" {
```
Comment (lbajolet-hashicorp) [inline builder/vmware/common/step_create_snapshot.go:22]:
```suggestion
	if *s.SnapshotName == "" {
		state.Put("snapshot_skipped", true)
		return multistep.ActionContinue
	}
```

Comment (tenthirtyam) [reply builder/vmware/common/step_create_snapshot.go]: Updated in bebc6a5.

**Review by lbajolet-hashicorp — APPROVED** [review]
LGTM!
