### PR TITLE
fix: generate default `netmap.conf`, if required

### LINKED ISSUE #65: VMware Workstation on Windows: "Incorrect path in network mappings"
Windows 11
VMware® Workstation 16 Pro (16.2.2 build-19200509)
Packer v1.7.10
Plugin pulled today

When running packer build on a freshly setup system it fails with:

"Could not determine network mappings from files in path: C:/Program Files (x86)/VMware/VMware Workstation"

Workstation 16 Pro has installed network files in "C:\ProgramData\VMware", the missing file is netmap.conf. If netmap.conf is placed in the directory stated and not "C:\ProgramData\VMware" the build continues to fail with the same message. I only found this out after realising netmap.conf could be made by editing the network config with vmware and by chance Packer started working. 

Originally I was putting a copy of netmap.conf in the stated directory and packer still wouldn't work. After using the network editor and it working I then tested Packer with the file only in one location at a time and it would not work under "C:/Program Files (x86)/VMware/VMware Workstation" which is the stated directory in the message. I'm guessing there was a change in structure at some point for VMware and the error message was overlooked.

Thanks
Luke

### PR DESCRIPTION
**Pull request by tenthirtyam**
### Description

Generates the `netmap.conf` in the default location if the file does not exist in the default path or the alternate path. The file generated is an exact match to the default based on a template.

There have been reported issues (GH, Discuss, blogs) of fresh installations of Workstation 17 (and 16) not generating the default file which will cause a build to fail on a newly configured system.

cc @mikeroySoft, Product Manager for Workstation.

### Reference

Closes #65

- [Discuss](https://discuss.hashicorp.com/t/solved-could-not-determine-network-mappings-on-vmware-iso-vmw-16-2-2/36265/2)
- [Blog](https://www.vgemba.net/vmware/Packer-Workstation-Error/#the-fix) by @cwestwater

### CODE REVIEW

File: builder/vmware/common/driver_workstation9.go [hunk 1]
```diff
@@ -173,33 +210,12 @@ func (d *Workstation9Driver) Verify() error {
...
-		pathNetworking := filepath.Join(libpath, "networking")
-		if _, err := os.Stat(pathNetworking); err != nil {
-			return nil, fmt.Errorf("error determining network mappings from files in path: %s", libpath)
-		}
-
-		// We were able to successfully stat the file.. So, now we can open a handle to it.
-		log.Printf("Located networking configuration file: %s", pathNetworking)
-		fd, err := os.Open(pathNetworking)
+		// Check if the network mapper configuration file exists.
+		mapper, err := checkNetmapConfExists()
```
Comment (nywilken) [inline builder/vmware/common/driver_workstation9.go:214]: I like this approach. The consolidation makes this code easier to read. I was surprised to learn that the checkNetmapConfExists also generates. To not make this function do more then what it should I suggest splitting out the logic in the function and making the call here. For example

```go
		mapper, err := checkNetmapConfExists()
		if err == nil {
		    return mapper, nil
		}
		
		if err != nil && runtime.GOOS != "windows" {
		   	// For non-Windows, if neither the default nor alternate
			// configuration paths exist, return an error.
			return nil, err
		}
		if !errors.Is(err, os.ErrNotExist) {
		   return nil, err
		}
		// For windows we can safely generate the network mapper configuration file in the default path.
		pathNetmap, err := generateNetmapConfig()
		if err != nil {
			log.Fatalf("error generating the absent network configuration file: %v", err)
			return nil, err
		}
		// If the file exists, attempt to read the newly generated
		// network mapper configuration file.
		return ReadNetmapConfig(pathNetmap)
```

File: builder/vmware/common/driver_workstation9.go [hunk 2]
```diff
@@ -215,3 +231,112 @@ func (d *Workstation9Driver) ToolsInstall() error {
...
+			return nil, fmt.Errorf("error determining network mappings from files in path: %s", libpath)
+		}
+	} else if err != nil {
+		// There was an error other than the file not existing.
+		return nil, err
+	}
+
+	// If the default network mapper configuration file exists, read the configuration.
+	log.Printf("Located the network mapper configuration file: %s", pathNetmap)
+	return ReadNetmapConfig(pathNetmap)
```
Comment (nywilken) [inline builder/vmware/common/driver_workstation9.go:283]: Instead of the nested if statements let's see if we can write this to return early when there is no more work to be done. We can also wrap the underlying error so that we can check above if it is an os.ErrNotExist error as a toggle for calling the generate function on Windows. 
For example 


```go
        // Check if the default network mapper configuration file exists.
	_, err := os.Stat(pathNetmap)
	if err == nil {
		// If the default network mapper configuration file exists, read the configuration.
		log.Printf("Located the network mapper configuration file: %s", pathNetmap)
		return ReadNetmapConfig(pathNetmap)
	}
	if !os.IsNotExist(err) {
		return nil, fmt.Errorf("error determining network mappings from files %w", err)
	}

	log.Printf("A network mapper configuration file does not exist in the default path: %s", pathNetmap)
	// The file does not exist, check the alternate configuration path.
	libpath, _ := workstationVMwareRoot()
	pathNetworking := filepath.Join(libpath, "networking")
	log.Printf("Checking alternate path for network mapper configuration file: %s", pathNetworking)
	_, err = os.Stat(pathNetworking)
	if err != nil { // If we get an error we wrap the error. The caller can check if it is a ErrNotExist and act accordingly
		return nil, fmt.Errorf("error determining network mappings from files %w", err)
	}

	// Alternate networking configuration path exists. Using this path.
	log.Printf("Located the network mapper configuration file: %s", pathNetworking)
	fd, err := os.Open(pathNetworking)
	if err != nil {
		return nil, err
	}
	defer fd.Close()

	// Then we pass the handle to the networking configuration parser.
	return ReadNetworkingConfig(fd)
```

**Review by nywilken — COMMENTED** [review]
I left a few suggestions. I'm still working through the PR.

File: builder/vmware/common/driver_workstation9.go (hunk 2 above)
Comment (tenthirtyam) [reply builder/vmware/common/driver_workstation9.go:283]: On it - will update and send back soon.

File: builder/vmware/common/driver_workstation9.go (hunk 1 above)
Comment (tenthirtyam) [reply builder/vmware/common/driver_workstation9.go:214]: On it - will update and send back soon.

File: builder/vmware/common/driver_workstation9.go (hunk 2 above)
Comment (tenthirtyam) [reply builder/vmware/common/driver_workstation9.go]: Resolved in https://github.com/hashicorp/packer-plugin-vmware/commit/2ebbe20b26e25aa4be8dd12291b20fc408d291ff and tested!

File: builder/vmware/common/driver_workstation9.go (hunk 1 above)
Comment (tenthirtyam) [reply builder/vmware/common/driver_workstation9.go:214]: Resolved in https://github.com/hashicorp/packer-plugin-vmware/commit/2ebbe20b26e25aa4be8dd12291b20fc408d291ff and tested!

**Review by nywilken — APPROVED** [review]
The updates look great. Thanks for tackling this PR.
